borg backups WIP

diff --git a/Common/.bin/bin/+backup b/Common/.bin/bin/+backup
--- a/Common/.bin/bin/+backup
+++ b/Common/.bin/bin/+backup
@@ -19,6 +19,104 @@ function firefox_profile() {
     echo "$PROFILE"
 }
 
+function borg_backup() {
+    if ! type borg >/dev/null 2>&1; then
+        echo "You need to install borg first, exiting..."
+        exit 1
+    fi
+
+    # derived information
+    export BORG_CACHE_DIR=/home/$USER/.cache/borg/
+
+    # Setting this, so the repo does not need to be given on the commandline:
+    # TODO: export BORG_REPO=ssh://username@example.com:2022/~/backup/main
+    export BORG_REPO=/run/media/$USER/Toshiba/borg
+
+    # # See the section "Passphrase notes" for more infos.
+    export BORG_PASSPHRASE=$(pass Apps/borgbackup)
+
+    # some helpers and error handling:
+    info() { printf "\n%s %s\n\n" "$(date)" "$*" >&2; }
+    trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
+
+    info "Starting backup"
+
+    # Backup the most important directories into an archive named after
+    # the machine this script is currently running on:
+
+    borg create \
+        --progress \
+        --stats \
+        --filter AME \
+        --list \
+        --show-rc \
+        --compression lz4 \
+        --exclude-caches \
+        --exclude '/home/*/.cache' \
+        --exclude '/home/*/.npm' \
+        --exclude '/home/*/.composer' \
+        --exclude '/home/*/.vagrant.d' \
+        --exclude '/home/*/Scaricati*' \
+        --exclude '/home/*/Virtualbox VMs*' \
+        --exclude '/home/*/VirtualBox VMs*' \
+        --exclude '/home/*/.local' \
+        --exclude '/home/*/.var' \
+        --exclude '/home/*/.nvidia*' \
+        --exclude '/home/*/.dropbox*' \
+        --exclude '/home/*/Dropbox' \
+        --exclude '/home/*/.bin' \
+        --exclude '/home/*/Workspace/Public/' \
+        --exclude 're:/vendor/' \
+        --exclude 're:/node_modules/' \
+        \
+        ::'{hostname}-{now}' \
+        /home/"$USER"/
+
+    backup_exit=$?
+
+    info "Pruning repository"
+
+    # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
+    # archives of THIS machine. The '{hostname}-' prefix is very important to
+    # limit prune's operation to this machine's archives and not apply to
+    # other machines' archives also:
+
+    borg prune \
+        --list \
+        --prefix '{hostname}-' \
+        --show-rc \
+        --keep-daily 7 \
+        --keep-weekly 4 \
+        --keep-monthly 6
+
+    prune_exit=$?
+
+    # actually free repo disk space by compacting segments
+
+    info "Compacting repository"
+
+    borg compact
+
+    compact_exit=$?
+
+    # use highest exit code as global exit code
+    global_exit=$((backup_exit > prune_exit ? backup_exit : prune_exit))
+    global_exit=$((compact_exit > global_exit ? compact_exit : global_exit))
+
+    if [ ${global_exit} -eq 0 ]; then
+        info "Backup, Prune, and Compact finished successfully"
+    elif [ ${global_exit} -eq 1 ]; then
+        info "Backup, Prune, and/or Compact finished with warnings"
+    else
+        info "Backup, Prune, and/or Compact finished with errors"
+    fi
+
+    exit ${global_exit}
+}
+
+borg_backup
+exit 0
+
 function init() {
     if [ -z "$1" ] || [ ! -d "$1" ]; then
         echo "Illegal arguments ($1 must exist and be a directory)"
