+crypt script does not depends on anything

diff --git a/Common/.bin/bin/+crypt b/Common/.bin/bin/+crypt
--- a/Common/.bin/bin/+crypt
+++ b/Common/.bin/bin/+crypt
@@ -10,7 +10,14 @@
 #   (symmetric) or "*.tar.gz.asc (asymmetric)"
 #
 
-. "$(dirname "$0")/../common.sh"
+check() {
+    if [ "$1" -ne 0 ]; then
+        echo ""
+        echo ">>> This is an error, do something else... We don't know what's wrong here!!!"
+        echo ""
+        exit "$1"
+    fi
+}
 
 function encrypt() {
     if [ -z "$1" ] || [ "$1" != "-s" ] && [ "$1" != "-a" ]; then
