update fedora...

diff --git a/Common/shell/post_install/llvm-latest b/Common/shell/post_install/llvm-latest
--- a/Common/shell/post_install/llvm-latest
+++ b/Common/shell/post_install/llvm-latest
@@ -3,6 +3,16 @@
 # add clang ${version} to Debian
 # https://gist.github.com/junkdog/70231d6953592cd6f27def59fe19e50d
 
+if [ ! -f /etc/debian_version ]; then
+    echo "Error: Debian is not running on this system, exiting..."
+    exit 1
+fi
+
+if ! hash apt 2> /dev/null; then
+    echo "Error: apt not installed on this system, exiting..."
+    exit 1
+fi
+
 update_alternatives() {
     local version=${1}
     local priority=${2}
